all:  Filtrar

Poligono:  Filtrar.o 
	g++  Filtrar.o  -o Filtrar

Poligono.o: Poligono.cpp PoligonoCont.h
	g++ -c Poligono.cpp

PoligonoTest.o: PoligonoTest.cpp 
	g++ -c PoligonoTest.cpp

clean:
	rm *.o Filtrar